import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Funnel_Sans } from 'next/font/google';

const funnelSans = Funnel_Sans({
  subsets: ['latin'],
  weight: ['300','400', '500', '600', '800'], // Wybierz potrzebne grubości
  display: 'swap',
  variable: '--font-funnel-sans', // Opcjonalnie: jako zmienna CSS
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" className={funnelSans.variable}>
      <body className={funnelSans.className}>
        {children}
      </body>
    </html>
  );
}
